CREATE TABLE IF NOT EXISTS crypto_payments (
  id BIGSERIAL PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending',
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE orders ADD COLUMN IF NOT EXISTS provider_ref TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS renew BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS period_end TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS kind TEXT;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS pay_via TEXT;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS renew BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS expires_on DATE;
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS provider_sub TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS member_until TIMESTAMPTZ;
